[env:DX_LR30_ST7789]
extends = esp32s3_base
board = ESP32-S3-WROOM-1-N4
board_level = extra
build_flags =
  ${esp32s3_base.build_flags}
  -D DX_LR30_ST7789
  -I variants/esp32s3/DX_LR30_ST7789
lib_deps =
  lovyan32/LovyanGFX@^0.5.0
  https://github.com/meshtastic/ESP32_Codec2/archive/633326c78ac251c059ab3a8c430fcdf25b41672f.zip
